import {
  applyMtrxTrn,
  applyMtrxDet,
  applyMtrxInv,
  applyMtrxScale,
  applyMtrxAdd,
  applyMtrxSub,
  applyMtrxMul,
  applyMtrxIdn,
  applyMtrxCon,
  applyMtrxRnrm,
  applyMtrxCnrm,
  applyMtrxTrace,
  applyMtrxTran,
  applyMtrxRsd,
  applyMtrxSvd,
  applyMtrxSchur,
  applyMtrxEigv,
  applyMtrxLu,
  applyMtrxQr,
} from "../logic/matrix/matrixOps";

import {
  matrAdd,
  matrSub,
  matrMul,
  matrTrn,
  matrInv,
  matrDet,
  matrIdn,
  matrTrace,
  matrRref,
  matrEigen,
  matrCholesky,
  matrLu,
  matrQr,
  matrSolve,
  matrToV2,
  matrToV3,
  matrToMat,
  matrToList,
  matrToArry,
  matrRowAdd,
  matrRowSub,
  matrColAdd,
  matrColSub,
  matrRdm,
  matrRanm,
  matrSize,
  matrDim,
  matrPut,
  matrGet,
  matrPuti,
  matrGeti,
  matrCon,
  matrDot,
  matrCross,
  matrSys,
  matrEditmat,
  matrWriter,
  matrLinSolve,
  matrNxt,
  matrPrev,
} from "../logic/matrix/matrOps";

import type { MatrixOpCode } from "./opCodes";
import type { CalcState } from "./calculatorState";

type StateOp = (state: CalcState) => CalcState;

export const matrixRegistry: Record<MatrixOpCode, StateOp> = {
  MTRX_TRN:   applyMtrxTrn,
  MTRX_DET:   applyMtrxDet,
  MTRX_INV:   applyMtrxInv,
  MTRX_SCALE: applyMtrxScale,
  MTRX_ADD:   applyMtrxAdd,
  MTRX_SUB:   applyMtrxSub,
  MTRX_MUL:   applyMtrxMul,
  MTRX_IDN:   applyMtrxIdn,
  MTRX_CON:   applyMtrxCon,
  MTRX_RNRM:  applyMtrxRnrm,
  MTRX_CNRM:  applyMtrxCnrm,
  MTRX_TRACE: applyMtrxTrace,
  MTRX_TRAN:  applyMtrxTran,
  MTRX_RSD:   applyMtrxRsd,
  MTRX_SVD:   applyMtrxSvd,
  MTRX_SCHUR: applyMtrxSchur,
  MTRX_EIGV:  applyMtrxEigv,
  MTRX_LU:    applyMtrxLu,
  MTRX_QR:    applyMtrxQr,
  MATR_ADD:       matrAdd,
  MATR_SUB:       matrSub,
  MATR_MUL:       matrMul,
  MATR_TRN:       matrTrn,
  MATR_INV:       matrInv,
  MATR_DET:       matrDet,
  MATR_IDN:       matrIdn,
  MATR_RREF:      matrRref,
  MATR_TRACE:     matrTrace,
  MATR_EIGEN:     matrEigen,
  MATR_CHOLESKY:  matrCholesky,
  MATR_LU:        matrLu,
  MATR_QR:        matrQr,
  MATR_SOLVE:     matrSolve,
  MATR_TO_V2:     matrToV2,
  MATR_TO_V3:     matrToV3,
  MATR_TO_MAT:    matrToMat,
  MATR_TO_LIST:   matrToList,
  MATR_TO_ARRY:   matrToArry,
  MATR_ROW_ADD:   matrRowAdd,
  MATR_ROW_SUB:   matrRowSub,
  MATR_COL_ADD:   matrColAdd,
  MATR_COL_SUB:   matrColSub,
  MATR_RDM:       matrRdm,
  MATR_RANM:      matrRanm,
  MATR_SIZE:      matrSize,
  MATR_DIM:       matrDim,
  MATR_PUT:       matrPut,
  MATR_GET:       matrGet,
  MATR_PUTI:      matrPuti,
  MATR_GETI:      matrGeti,
  MATR_CON:       matrCon,
  MATR_DOT:       matrDot,
  MATR_CROSS:     matrCross,
  MATR_SYS:       matrSys,
  MATR_EDITMAT:   matrEditmat,
  MATR_WRITER:    matrWriter,
  MATR_LIN_SOLVE: matrLinSolve,
  MATR_NXT:       matrNxt,
  MATR_PREV:      matrPrev,
};
